//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JobPortal.Web.com.stescodes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="contactswsSoap", Namespace="http://tempuri.org/")]
    public partial class contactsws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAuthenticationUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccessTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabContactsOAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabContactsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public contactsws() {
            this.Url = global::JobPortal.Web.Properties.Settings.Default.JobPortal_Web_com_stescodes_contactsws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAuthenticationUrlCompletedEventHandler GetAuthenticationUrlCompleted;
        
        /// <remarks/>
        public event GetAccessTokenCompletedEventHandler GetAccessTokenCompleted;
        
        /// <remarks/>
        public event GrabContactsOAuthCompletedEventHandler GrabContactsOAuthCompleted;
        
        /// <remarks/>
        public event GrabContactsCompletedEventHandler GrabContactsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAuthenticationUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Authentication GetAuthenticationUrl(string servicename, string ConsumerKey, string ConsumerSecret, string callbackurl) {
            object[] results = this.Invoke("GetAuthenticationUrl", new object[] {
                        servicename,
                        ConsumerKey,
                        ConsumerSecret,
                        callbackurl});
            return ((Authentication)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthenticationUrlAsync(string servicename, string ConsumerKey, string ConsumerSecret, string callbackurl) {
            this.GetAuthenticationUrlAsync(servicename, ConsumerKey, ConsumerSecret, callbackurl, null);
        }
        
        /// <remarks/>
        public void GetAuthenticationUrlAsync(string servicename, string ConsumerKey, string ConsumerSecret, string callbackurl, object userState) {
            if ((this.GetAuthenticationUrlOperationCompleted == null)) {
                this.GetAuthenticationUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthenticationUrlOperationCompleted);
            }
            this.InvokeAsync("GetAuthenticationUrl", new object[] {
                        servicename,
                        ConsumerKey,
                        ConsumerSecret,
                        callbackurl}, this.GetAuthenticationUrlOperationCompleted, userState);
        }
        
        private void OnGetAuthenticationUrlOperationCompleted(object arg) {
            if ((this.GetAuthenticationUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthenticationUrlCompleted(this, new GetAuthenticationUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccessToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccessToken GetAccessToken(string servicename, string ConsumerKey, string ConsumerSecret, string callbackurl, string Token, string TokenSecret, string TokenVerifier) {
            object[] results = this.Invoke("GetAccessToken", new object[] {
                        servicename,
                        ConsumerKey,
                        ConsumerSecret,
                        callbackurl,
                        Token,
                        TokenSecret,
                        TokenVerifier});
            return ((AccessToken)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccessTokenAsync(string servicename, string ConsumerKey, string ConsumerSecret, string callbackurl, string Token, string TokenSecret, string TokenVerifier) {
            this.GetAccessTokenAsync(servicename, ConsumerKey, ConsumerSecret, callbackurl, Token, TokenSecret, TokenVerifier, null);
        }
        
        /// <remarks/>
        public void GetAccessTokenAsync(string servicename, string ConsumerKey, string ConsumerSecret, string callbackurl, string Token, string TokenSecret, string TokenVerifier, object userState) {
            if ((this.GetAccessTokenOperationCompleted == null)) {
                this.GetAccessTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccessTokenOperationCompleted);
            }
            this.InvokeAsync("GetAccessToken", new object[] {
                        servicename,
                        ConsumerKey,
                        ConsumerSecret,
                        callbackurl,
                        Token,
                        TokenSecret,
                        TokenVerifier}, this.GetAccessTokenOperationCompleted, userState);
        }
        
        private void OnGetAccessTokenOperationCompleted(object arg) {
            if ((this.GetAccessTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccessTokenCompleted(this, new GetAccessTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabContactsOAuth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Contacts GrabContactsOAuth(string ServiceName, string Token, string TokenSecret, string TokenVerifier, string UID, string Signature, string ConsumerKey, string ConsumerSecret) {
            object[] results = this.Invoke("GrabContactsOAuth", new object[] {
                        ServiceName,
                        Token,
                        TokenSecret,
                        TokenVerifier,
                        UID,
                        Signature,
                        ConsumerKey,
                        ConsumerSecret});
            return ((Contacts)(results[0]));
        }
        
        /// <remarks/>
        public void GrabContactsOAuthAsync(string ServiceName, string Token, string TokenSecret, string TokenVerifier, string UID, string Signature, string ConsumerKey, string ConsumerSecret) {
            this.GrabContactsOAuthAsync(ServiceName, Token, TokenSecret, TokenVerifier, UID, Signature, ConsumerKey, ConsumerSecret, null);
        }
        
        /// <remarks/>
        public void GrabContactsOAuthAsync(string ServiceName, string Token, string TokenSecret, string TokenVerifier, string UID, string Signature, string ConsumerKey, string ConsumerSecret, object userState) {
            if ((this.GrabContactsOAuthOperationCompleted == null)) {
                this.GrabContactsOAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabContactsOAuthOperationCompleted);
            }
            this.InvokeAsync("GrabContactsOAuth", new object[] {
                        ServiceName,
                        Token,
                        TokenSecret,
                        TokenVerifier,
                        UID,
                        Signature,
                        ConsumerKey,
                        ConsumerSecret}, this.GrabContactsOAuthOperationCompleted, userState);
        }
        
        private void OnGrabContactsOAuthOperationCompleted(object arg) {
            if ((this.GrabContactsOAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabContactsOAuthCompleted(this, new GrabContactsOAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabContacts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Contacts GrabContacts(string servicename, string strUserName, string strPassword, string signature) {
            object[] results = this.Invoke("GrabContacts", new object[] {
                        servicename,
                        strUserName,
                        strPassword,
                        signature});
            return ((Contacts)(results[0]));
        }
        
        /// <remarks/>
        public void GrabContactsAsync(string servicename, string strUserName, string strPassword, string signature) {
            this.GrabContactsAsync(servicename, strUserName, strPassword, signature, null);
        }
        
        /// <remarks/>
        public void GrabContactsAsync(string servicename, string strUserName, string strPassword, string signature, object userState) {
            if ((this.GrabContactsOperationCompleted == null)) {
                this.GrabContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabContactsOperationCompleted);
            }
            this.InvokeAsync("GrabContacts", new object[] {
                        servicename,
                        strUserName,
                        strPassword,
                        signature}, this.GrabContactsOperationCompleted, userState);
        }
        
        private void OnGrabContactsOperationCompleted(object arg) {
            if ((this.GrabContactsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabContactsCompleted(this, new GrabContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Authentication {
        
        private AuthDetails detailsField;
        
        private string errorField;
        
        private string serviceField;
        
        /// <remarks/>
        public AuthDetails details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthDetails {
        
        private string tokenField;
        
        private string tokenSecretField;
        
        private string authUrlField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string tokenSecret {
            get {
                return this.tokenSecretField;
            }
            set {
                this.tokenSecretField = value;
            }
        }
        
        /// <remarks/>
        public string authUrl {
            get {
                return this.authUrlField;
            }
            set {
                this.authUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class userInfo {
        
        private string emailField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class contactdetails {
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Contacts {
        
        private string errorField;
        
        private string serviceField;
        
        private contactdetails[] listField;
        
        private userInfo uInfoField;
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public contactdetails[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <remarks/>
        public userInfo uInfo {
            get {
                return this.uInfoField;
            }
            set {
                this.uInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccessTokenDetails {
        
        private string tokenField;
        
        private string tokenSecretField;
        
        private string idField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string tokenSecret {
            get {
                return this.tokenSecretField;
            }
            set {
                this.tokenSecretField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccessToken {
        
        private AccessTokenDetails detailsField;
        
        private string errorField;
        
        private string serviceField;
        
        /// <remarks/>
        public AccessTokenDetails details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAuthenticationUrlCompletedEventHandler(object sender, GetAuthenticationUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthenticationUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthenticationUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Authentication Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Authentication)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAccessTokenCompletedEventHandler(object sender, GetAccessTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccessTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccessTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccessToken Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccessToken)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GrabContactsOAuthCompletedEventHandler(object sender, GrabContactsOAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrabContactsOAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrabContactsOAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Contacts Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contacts)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GrabContactsCompletedEventHandler(object sender, GrabContactsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrabContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrabContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Contacts Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contacts)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591