//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public long Id { get; set; }
        public int Type { get; set; }
        public long UserId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<long> ReferenceId { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public bool Unread { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
