//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public Alert()
        {
            this.AlertHistories = new HashSet<AlertHistory>();
            this.Unsubscriptions = new HashSet<Unsubscription>();
            this.AlertSettings = new HashSet<AlertSetting>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public bool Daily { get; set; }
        public bool Weekly { get; set; }
        public bool Monthly { get; set; }
        public int Times { get; set; }
        public bool Hourly { get; set; }
        public bool Configurable { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AlertHistory> AlertHistories { get; set; }
        public virtual ICollection<Unsubscription> Unsubscriptions { get; set; }
        public virtual ICollection<AlertSetting> AlertSettings { get; set; }
    }
}
