//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedPeople
    {
        public long Id { get; set; }
        public long BlockedId { get; set; }
        public long BlockerId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual UserProfile BlockedUser { get; set; }
        public virtual UserProfile Blocker { get; set; }
    }
}
