//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string DeletedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsConnected { get; set; }
        public bool IsBlocked { get; set; }
        public bool Initiated { get; set; }
        public string Phone { get; set; }
        public bool Sent { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public bool Unsubscribed { get; set; }
        public Nullable<System.DateTime> LastReminderDate { get; set; }
        public bool IsValid { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
