//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hit
    {
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
