//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public Interview()
        {
            this.FollowUps = new HashSet<FollowUp>();
            this.InterviewDiscussions = new HashSet<InterviewDiscussion>();
            this.InterviewNotes = new HashSet<InterviewNote>();
        }
    
        public long Id { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.Guid TrackingId { get; set; }
        public long UserId { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public string InterviewTime { get; set; }
        public string Interviewer { get; set; }
        public string Description { get; set; }
        public int Round { get; set; }
    
        public virtual Tracking Tracking { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<FollowUp> FollowUps { get; set; }
        public virtual ICollection<InterviewDiscussion> InterviewDiscussions { get; set; }
        public virtual ICollection<InterviewNote> InterviewNotes { get; set; }
    }
}
