//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invite
    {
        public long Id { get; set; }
        public string Mobile { get; set; }
        public bool Invited { get; set; }
        public long UserId { get; set; }
        public string MessageSID { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public bool IsConnected { get; set; }
        public System.DateTime DateInvited { get; set; }
        public Nullable<System.DateTime> LastReminderDate { get; set; }
    }
}
