//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public List()
        {
            this.UserCountries = new HashSet<UserProfile>();
            this.UserStates = new HashSet<UserProfile>();
            this.ResumeCountries = new HashSet<Resume>();
            this.ResumeStates = new HashSet<Resume>();
            this.QualifiedResumes = new HashSet<Resume>();
            this.Newsletters = new HashSet<Newsletter>();
            this.CountryTrackingDetails = new HashSet<TrackingDetail>();
            this.StateTrackingDetails = new HashSet<TrackingDetail>();
            this.JobCountries = new HashSet<Job>();
            this.Jobs1 = new HashSet<Job>();
            this.Jobs2 = new HashSet<Job>();
            this.JobsStates = new HashSet<Job>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentList { get; set; }
        public string Text { get; set; }
        public string Value { get; set; }
        public bool IsDefault { get; set; }
        public int contientId { get; set; }
        public string Code { get; set; }
        public bool IsDeveloped { get; set; }
    
        public virtual ICollection<UserProfile> UserCountries { get; set; }
        public virtual ICollection<UserProfile> UserStates { get; set; }
        public virtual ICollection<Resume> ResumeCountries { get; set; }
        public virtual ICollection<Resume> ResumeStates { get; set; }
        public virtual ICollection<Resume> QualifiedResumes { get; set; }
        public virtual ICollection<Newsletter> Newsletters { get; set; }
        public virtual ICollection<TrackingDetail> CountryTrackingDetails { get; set; }
        public virtual ICollection<TrackingDetail> StateTrackingDetails { get; set; }
        public virtual ICollection<Job> JobCountries { get; set; }
        public virtual ICollection<Job> Jobs1 { get; set; }
        public virtual ICollection<Job> Jobs2 { get; set; }
        public virtual ICollection<Job> JobsStates { get; set; }
    }
}
