//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListJob1C
    {
        public int id { get; set; }
        public string CompanyName { get; set; }
        public string AboutCompany { get; set; }
        public Nullable<int> job_id { get; set; }
        public byte[] CompanyLogos { get; set; }
    }
}
