//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public long Id { get; set; }
        public string Username { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public string Browser { get; set; }
        public string Comments { get; set; }
        public int MaxRows { get; set; }
    }
}
