//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public int Id { get; set; }
        public int Frequency { get; set; }
        public int Type { get; set; }
        public long CountryId { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Content { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsSent { get; set; }
    
        public virtual List Country { get; set; }
    }
}
