//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public byte[] Image { get; set; }
        public string Type { get; set; }
        public string Area { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
        public string Reason { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] NewImage { get; set; }
        public string ImageSize { get; set; }
        public string NewImageSize { get; set; }
        public bool InEditMode { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
