//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileView
    {
        public long Id { get; set; }
        public long ProfileId { get; set; }
        public Nullable<long> UserId { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public bool Unread { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
