//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMJobList
    {
        public long Id { get; set; }
        public string CountryName { get; set; }
        public string CompanyName { get; set; }
        public string JobTitle { get; set; }
        public string MSkills { get; set; }
        public string JobDescription { get; set; }
        public string JobResponsibility { get; set; }
        public string JobRequirement { get; set; }
        public string JobLink { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string EmailSent { get; set; }
        public string Accepted { get; set; }
        public string JobSource { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public string Summary { get; set; }
        public string Overview { get; set; }
        public string PublishedDate { get; set; }
        public string ClosingDate { get; set; }
        public Nullable<long> EmployerId { get; set; }
        public string EmployerUrl { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string JobUrl { get; set; }
        public string Category { get; set; }
        public string Specialization { get; set; }
        public string Qualification { get; set; }
        public string MinimumExperience { get; set; }
        public string MaximumExperienc { get; set; }
        public string Currencye { get; set; }
        public string MaximumExperience { get; set; }
        public string MinimumSalary { get; set; }
        public string MaximumSalary { get; set; }
        public string JobType { get; set; }
        public string CategoryId { get; set; }
        public string SpecializationId { get; set; }
        public string QualificationId { get; set; }
        public string EmploymentTypeId { get; set; }
        public string ImageType { get; set; }
        public string Description { get; set; }
        public string Currency { get; set; }
        public string JobID { get; set; }
        public string Zip { get; set; }
        public string Status { get; set; }
        public Nullable<long> TotalViews { get; set; }
        public string JobLevel { get; set; }
        public byte[] Image { get; set; }
    }
}
