//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public Tracking()
        {
            this.Interviews = new HashSet<Interview>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<long> ResumeId { get; set; }
        public Nullable<long> JobId { get; set; }
        public int Type { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public bool IsDeleted { get; set; }
        public long UserId { get; set; }
        public Nullable<long> JobseekerId { get; set; }
        public bool IsDownloaded { get; set; }
        public bool IsMessageSent { get; set; }
        public bool IsInvited { get; set; }
        public bool IsViewed { get; set; }
    
        public virtual Resume Resume { get; set; }
        public virtual TrackingDetail TrackingDetail { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile Jobseeker { get; set; }
        public virtual Job Job { get; set; }
    }
}
