//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingDetail
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public int SpecializationId { get; set; }
        public long CountryId { get; set; }
        public Nullable<long> StateId { get; set; }
        public string FileName { get; set; }
        public string Content { get; set; }
    
        public virtual Tracking Tracking { get; set; }
        public virtual List Country { get; set; }
        public virtual List State { get; set; }
        public virtual Specialization Category { get; set; }
        public virtual SubSpecialization Specialization { get; set; }
    }
}
