//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unsubscription
    {
        public long Id { get; set; }
        public int AlertId { get; set; }
        public bool Unsubscribed { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Alert Alert { get; set; }
    }
}
