//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Skills
    {
        public long UserId { get; set; }
        public string SkillName { get; set; }
        public Nullable<long> Rating { get; set; }
        public Nullable<decimal> Percentage_Cal { get; set; }
        public int UType { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
