//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Experience
    {
        public long UserId { get; set; }
        public string Employer { get; set; }
        public string Industry { get; set; }
        public string Roles { get; set; }
        public Nullable<int> FromMonth { get; set; }
        public Nullable<int> ToMonth { get; set; }
        public Nullable<long> FromYr { get; set; }
        public Nullable<long> ToYr { get; set; }
        public string Responsibilities { get; set; }
        public int UType { get; set; }
        public string CountryId { get; set; }
        public string Category { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
