//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Certificate
    {
        public long UserId { get; set; }
        public string Certificate { get; set; }
        public string Institute { get; set; }
        public string Logo { get; set; }
        public string LogoType { get; set; }
        public Nullable<int> UType { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
