//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCampaign
    {
        public UserCampaign()
        {
            this.UserCampaign1 = new HashSet<UserCampaign>();
        }
    
        public long Id { get; set; }
        public long CampaignId { get; set; }
        public long UserId { get; set; }
        public bool Unread { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Sent { get; set; }
    
        public virtual ICollection<UserCampaign> UserCampaign1 { get; set; }
        public virtual UserCampaign UserCampaign2 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
