//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteList
    {
        public long Id { get; set; }
        public string CountryName { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string EmailSent { get; set; }
        public string Accepted { get; set; }
        public string Name { get; set; }
        public string CompanyLogo { get; set; }
        public string Logo { get; set; }
        public string Category { get; set; }
        public string companylogoslink { get; set; }
        public string Company_Mail { get; set; }
    }
}
