CREATE TABLE [dbo].[exceljobs] (
    [id]              INT            IDENTITY (1, 1) NOT NULL,
    [employer_id]     BIGINT         NOT NULL,
    [title]           NVARCHAR (255) NOT NULL,
    [jobdetail]       NVARCHAR (MAX) NOT NULL,
    [job_publishdate] DATETIME       NULL,
    [job_closingdate] DATETIME       NULL,
    [isactive]        BIT            NOT NULL,
    [isdeleted]       BIT            NOT NULL,
    [isexpired]       BIT            NOT NULL,
    [createdate]      DATETIME       CONSTRAINT [DF_exceljobs_createdate] DEFAULT (getdate()) NOT NULL,
    [lastmodifydate]  DATETIME       CONSTRAINT [DF_exceljobs_lastmodifydate] DEFAULT (getdate()) NOT NULL,
    [createdby]       NVARCHAR (255) NOT NULL,
    [lastmodifyby]    NVARCHAR (255) NOT NULL,
    [siteId]          INT            NULL,
    [jobkeywords]     NVARCHAR (200) NULL,
    [isFeaturedJob]   BIT            NULL,
    [JobViewCount]    INT            NULL,
    [Country]         INT            NULL,
    [StateName]       VARCHAR (100)  NULL,
    [Zipcode]         VARCHAR (15)   NULL,
    [StateId]         INT            NULL,
    [IsSiteJob]       BIT            CONSTRAINT [DF_exceljobs_IsSiteJob] DEFAULT ((1)) NOT NULL,
    [SalaryRange]     NVARCHAR (50)  NULL,
    [Currency]        NVARCHAR (100) NULL,
    [SenderReference] BIGINT         NULL,
    [JobXml]          TEXT           NULL,
    [RedirectionUrl]  NVARCHAR (300) NULL,
    [transfered]      BIT            NOT NULL,
    CONSTRAINT [PK_exceljobs] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_exceljobs_employer] FOREIGN KEY ([employer_id]) REFERENCES [dbo].[Employers] ([Id]),
    CONSTRAINT [FK_exceljobs_site] FOREIGN KEY ([siteId]) REFERENCES [dbo].[site] ([id])
);

