CREATE TABLE [dbo].[Resumes] (
    [Id]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [CandidateId]            BIGINT          NULL,
    [Title]                  NVARCHAR (100)  NOT NULL,
    [CategoryId]             INT             NULL,
    [SpecializationId]       INT             NULL,
    [CountryId]              BIGINT          NULL,
    [StateId]                BIGINT          NULL,
    [City]                   NVARCHAR (150)  NULL,
    [Experience]             TINYINT         NULL,
    [MinimumAge]             TINYINT         NULL,
    [MaximumAge]             TINYINT         NULL,
    [DrawingSalary]          DECIMAL (18)    NULL,
    [ExpectedSalary]         DECIMAL (18)    NULL,
    [Qualification]          NVARCHAR (MAX)  NULL,
    [Summary]                NVARCHAR (MAX)  NULL,
    [ProfessionalExperience] NVARCHAR (MAX)  NULL,
    [Skills]                 NVARCHAR (MAX)  NULL,
    [Education]              NVARCHAR (MAX)  NULL,
    [PhotoImage]             VARBINARY (MAX) NULL,
    [AttachedFile]           VARBINARY (MAX) NULL,
    [Type]                   NVARCHAR (5)    NULL,
    [CreatedBy]              NVARCHAR (255)  NOT NULL,
    [DateCreated]            DATETIME        CONSTRAINT [DF_resume_createdate] DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]              NVARCHAR (255)  NULL,
    [DateUpdated]            DATETIME        CONSTRAINT [DF_resume_lastmodifydate] DEFAULT (getdate()) NULL,
    [IsDeleted]              BIT             CONSTRAINT [DF_Resumes_IsDeleted] DEFAULT ((0)) NOT NULL,
    [IsActive]               BIT             CONSTRAINT [DF_resume_isActive] DEFAULT ((1)) NOT NULL,
    [IsBulkResume]           BIT             NULL,
    [ResumeHits]             INT             CONSTRAINT [DF_resume_ResumeViewCount] DEFAULT ((0)) NOT NULL,
    [Keywords]               NVARCHAR (200)  NULL,
    [Photo]                  NVARCHAR (255)  NULL,
    [Privacy]                BIT             CONSTRAINT [DF_Resumes_Privacy] DEFAULT ((0)) NULL,
    [Country]                NVARCHAR (150)  NULL,
    [ResumeStateAbbr]        NVARCHAR (5)    NULL,
    [PublicProfileUrl]       NVARCHAR (150)  NULL,
    [UploadedResumeFile]     NVARCHAR (255)  NULL,
    CONSTRAINT [PK_resume] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Resumes_Candidates] FOREIGN KEY ([CandidateId]) REFERENCES [dbo].[Candidates] ([Id]),
    CONSTRAINT [FK_Resumes_Categories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Specializations] ([Id]),
    CONSTRAINT [FK_Resumes_CountryList] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Lists] ([Id]),
    CONSTRAINT [FK_Resumes_Specializations] FOREIGN KEY ([SpecializationId]) REFERENCES [dbo].[SubSpecializations] ([Id]),
    CONSTRAINT [FK_Resumes_StateList] FOREIGN KEY ([StateId]) REFERENCES [dbo].[Lists] ([Id])
);



