name: Deploy ASP.NET Core app to Azure Web App

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Joblistingdev    
  AZURE_WEBAPP_PACKAGE_PATH: 'JobPortal.Web/bin'      
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@v4
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet build --configuration Release JobPortal.Web/JobPortal.Web.csproj
          dotnet publish JobPortal.Web/JobPortal.Web.csproj -c Release -o ./bin
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CF75295A3BC947D5BDCC8088A7D72347 }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
